CH = {
 'n': 18,
 't': 'Financial Management Control System in the Public Sector',
 'brief': 'The three control structures over government revenue and expenditure — '
          'legislative, executive and treasury/departmental — the Vote Book, the Efficiency '
          'Unit, and finance/audit committees.',
 'outcomes': [
   'Appreciate what financial control in public sector organisations means',
   'Identify the various executive and legislative controls exerted to ensure efficient '
   "use of taxpayers' money",
   'Explain treasury and departmental controls, virement and cash management',
   'Describe the purpose and format of the Vote Book',
   'Explain the roles of the Efficiency Unit, Finance and General-Purpose Committee, and '
   'Audit Committee',
 ],
 'secs': [
  {'n': '18.1', 't': 'Introduction', 'b': [
    {'def': {'t': 'Expenditure control', 'd': 'the strings of coordinated actions taken to '
                  'ensure all expenditure is "wholly", "necessarily", "reasonably" and '
                  '"exclusively" incurred for the purposes for which it is meant. Control '
                  'structures broadly ensure that all revenue generated by government is paid '
                  'into the main government account or the **Consolidated Revenue Fund**.'}},
    {'p': 'Revenue-generating departments pay collections into "**collection bank accounts**" '
          'for onward transfer into government accounts with the Central Bank. Where a '
          'department is legislatively allowed to utilise some of its collections, it must '
          'follow the necessary procedures to properly account for the money used.'},
    {'key': 'Three main control structures exist to ensure government revenue is not '
            'misappropriated: **"Parliamentary" (Legislative)**, **"Treasury"** and '
            '**"Departmental"** controls.'},
  ]},

  {'n': '18.2', 't': 'The concept of financial control', 'b': [
    {'p': 'Public sector financial control has to do with:'},
    {'ol': [
      'Budgeting for public revenue and expenditure over an appropriate time span;',
      'Recording the revenue collected and expenditure incurred;',
      'Comparing actual results with the targets set; and',
      'Establishing systems for information flow and control.',
    ]},
  ]},

  {'n': '18.3', 't': 'Legislative control', 'b': [
    {'p': 'The **National Assembly** is the supreme authority on the nation\'s finances. '
          'Legislative control is both **"ante-natal"** (considering and approving the '
          'estimates the President submits) and **"post-natal"** (reviewing transactions '
          'after payment). No public fund may be spent without National Assembly approval — '
          'though **Section 82 of the 1999 Constitution** empowers the President to spend '
          'from the Consolidated Revenue Fund to run the Federation for **not more than six '
          '(6) months**, or until the Appropriation Act takes effect, whichever is earlier.'},
    {'p': 'This control matters because Parliament is independent of the Executive (which the '
          'ruling party forms). Parliament achieves financial control through:'},
    {'h4': '(a) Public finance committee'},
    {'p': 'A sub-committee of the National Assembly, responsible for receiving the '
          '**Appropriation Bill** (the annual revenue/expenditure estimates and other '
          'government proposals) for the National Assembly\'s consideration.'},
    {'h4': '(b) Appropriation committee'},
    {'p': 'Concerned with passing the Appropriation Bill into the **Appropriation Act**, '
          'authorising the estimates after examination by various sub-committees. This '
          'committee is, in effect, the **whole National Assembly** when it sits to pass the '
          'Appropriation Act.'},
    {'h4': '(c) Examination sub-committees'},
    {'p': 'Sub-committees responsible for examining individual organisations\' estimates and '
          'monitoring their expenditure. Proper performance of this role is a major control '
          'mechanism known as the execution of **oversight functions**.'},
    {'h4': '(d) Public Accounts Committee (PAC)'},
    {'def': {'t': 'Public Accounts Committee (PAC)', 'd': 'a body established by law to study '
                  'and examine the Auditor-General\'s reports — especially fraud or '
                  'embezzlement of public funds — expose waste, corruption or inefficiency, '
                  'and make recommendations to the National/State Assembly. Empowered to '
                  'examine the audited accounts of the Federation, public offices, and the '
                  'Auditor-General\'s report thereon.'}},
    {'p': '**Role of the PAC:**'},
    {'ol': [
      'Examine the accounts showing appropriation of sums granted by the Legislature to meet '
      'public expenditure, together with the Auditor-General\'s report;',
      'Ensure ministries spend in accordance with Legislative approval, and bring instances '
      'of extravagance, loss, infructuous expenditure and lack of financial integrity to the '
      'Assembly\'s notice;',
      'Send for any person, papers and records, report to the Legislature from time to time, '
      'and sit notwithstanding an adjournment of the Assembly;',
      'Examine any accounts/report of statutory corporations and boards after presentation to '
      'the House of Assembly, and report thereon;',
      'Enquire into the Auditor-General\'s report on any pre-payment audit query overruled by '
      'a Chief Executive, and report it to the Assembly;',
      'Has, in recent years, extended its scope to policy issues and accounts outside the '
      'appropriation accounts.',
    ]},
    {'p': '**Weaknesses of the PAC:**'},
    {'ul': [
      'Heavy turnover of PAC membership;',
      'Difficulty distinguishing "policy" issues from "administration" issues;',
      'The unclear status of public servants before the PAC and in the accountability system '
      'generally;',
      'Many members do not value the assignment, and lack appropriate background/experience;',
      'Lack of rules surrounding public servants\' testimony before the PAC;',
      'Heavy reliance on the Office of the Auditor-General for its agenda and investigative '
      'resources, leaving it little capacity or desire for independent investigation;',
      'A general lack of interest among legislators in accountability issues.',
    ]},
    {'h3': '18.3.1 Legislative control in Ghana'},
    {'p': '**(a) The Audit Service in Ghana** — responsible for examining public accounts to '
          'attest to the use of public funds sanctioned by Parliament at the year\'s start, '
          'assisting Parliament (via the Public Accounts Committee) by examining all '
          'government organisations\' accounts.'},
    {'p': '**(b) The concept of Appropriation in Ghana** — the procedure by which national '
          'revenue is made available annually to the Executive to finance its programmes. '
          'Every year, public sector undertakings prepare budgets (**supply estimates**) for '
          'legislative approval; an **Appropriation Bill** covers the combined estimates, '
          'passed into an **Appropriation Act** after examination and debate. Under '
          '**Section 25(2) of the FAA**, expenditure estimates are classified under programmes '
          'or activities in the Appropriation Bill, forwarded to Parliament to authorise the '
          'issue of money from the Consolidated Fund (or another appropriate fund).'},
    {'p': 'Functions of an Appropriation Act: **(i)** authorise the organisations\' estimates; '
          '**(ii)** give agreement to the **Ambit of the Vote**; **(iii)** act as a reference '
          'point for disagreements; **(iv)** denote, by implication, activities outside '
          'authorised areas as **ultra vires**.'},
    {'p': 'Before a budget year starts, a **Provisional Appropriation Act** authorises finances '
          'for government organisations to operate (normally for the first three months) '
          'until examinations/debates finish — these finances are **Provisional '
          'Appropriations** or **Votes on account**, deductible from each organisation\'s '
          'final approved amount. **Article 180 of the 1992 Constitution of Ghana** requires '
          'the President to call for such Provisional Appropriations. Approved estimates '
          'become **Votes**; the description of purposes for which they may be used is the '
          '**Ambit of the Vote**.'},
    {'p': '**(c) Appropriations-in-Aid** — any income a department receives apart from '
          'releases from the Consolidated Fund; deducted from the total supply estimates/'
          'appropriations the organisation needs, reducing the amount required from the '
          'Consolidated Fund.'},
  ]},

  {'n': '18.4', 't': 'The executive control', 'b': [
    {'p': 'The **Executive** — the President and cabinet (or, at State level, the Governor and '
          'cabinet) — has responsibility for efficient, effective administration of the '
          'country, politically and economically. The Constitution creates the **Legislature** '
          'and the **Judiciary** as separate arms, for checks and balances; all Presidential '
          'measures/policies are subject to Legislative approval within the Constitution.'},
    {'p': 'Under **Section 81(1) of the Constitution**, "The President shall cause to be '
          'prepared and laid before each House of the National Assembly, at any time in each '
          'financial year, estimates of revenue and expenditure of the Federation for the '
          'following financial year." The President appoints a **Cabinet Committee on '
          'Estimates** to advise on contemplated policy measures, transmitted to the **Budget '
          'Department in the Presidency**, leading to budget preparation guidelines and '
          'effective supervision of all budget-operation agencies. Any unit whose requirements '
          'exceed the issued "control figures" must defend the excess request.'},
    {'p': 'The Executive controls government expenditure through:'},
    {'ol': [
      'Determination of monetary and fiscal policies in general;',
      'Compilation and tentative approval of the Nation\'s budget;',
      'Appointment of the Auditor-General at all tiers of government;',
      'Issuance of budgetary guidelines;',
      'Introduction of "due process" guidelines;',
      'Introduction of e-payment, e-receipt and e-banking systems;',
      'Introduction of the **Public Procurement and Fiscal Responsibility Act, 2007**.',
    ]},
  ]},

  {'n': '18.5', 't': 'Ministry of Finance control', 'b': [
    {'p': 'Ministries present the Minister of Finance with proposed expenditure budgets that '
          'are necessary, reasonable and economical. Beyond the annual activities, the '
          'Minister\'s approval is required for every item of new expenditure, any increase '
          'beyond the amount originally authorised, and any transfer of funds between heads/'
          'subheads.'},
    {'note': 'All warrants authorising the Accountant-General to release funds from the '
             'Consolidated Revenue Fund (recurrent expenditure) or the Capital Development '
             'Fund (capital expenditure) must be issued and signed by the **Minister of '
             'Finance**.'},
    {'h4': '(a) Virement'},
    {'def': {'t': 'Virement', 'd': 'an authorised transfer from one **sub-head** to another '
                  '**sub-head, within the same head**.'}},
    {'p': 'A virement warrant may be issued: **(i)** when circumstances unforeseen when the '
          'annual estimates were framed require it; **(ii)** when additional provision is '
          'needed under one sub-head while an equivalent saving can be made under another '
          'sub-head of the same head.'},
    {'p': '**Conditions for virement:**'},
    {'ol': [
      'The amount vired from a sub-head under overhead costs, within a financial year, must '
      'not exceed **10%** of the approved estimate for each such sub-head;',
      'Virement must not create a new sub-head, or re-introduce items disallowed by the '
      'National Assembly during the budget process;',
      'Virement does not apply to Auditor-General queries on improper expenditure already '
      'incurred by an MDA;',
      'Approval is by the National Assembly, conveyed by the Minister of Finance to the MDA;',
      'A register must be kept of all virements made;',
      'Details of virements authorised must be forwarded within **one month** of approval to '
      'the ministry concerned, with copies to the Accountant-General and Auditor-General for '
      'the Federation.',
    ]},
    {'h4': '(b) Cash management'},
    {'def': {'t': 'Cash management', 'd': 'a component of good financial governance — ensuring '
                  'cash resources are spent to maximize citizen benefit, and are available in '
                  'a predictable, smooth manner for effective, efficient service delivery. '
                  'Requires: cash flow forecasting and planning; integrated cash and debt '
                  'management; active liquidity management; and efficient banking and payment '
                  'arrangements.'}},
    {'p': '**Objectives:** minimize costs within a prudent risk level; give a consolidated '
          'view of Government cash resources; ensure adequate cash to pay expenditures when '
          'due; maximize returns on idle cash; manage risk by investing temporary surpluses; '
          'develop good practice for daily cash-balance management; take advantage of modern '
          'banking systems/instruments; minimize borrowing.'},
    {'h4': 'Structure and institutional arrangement for FGN cash management'},
    {'p': '**Federal Cash Management Policy Committee** — chaired by the Honourable Minister '
          'of Finance (HMF), with overall responsibility for FGN cash planning/management. '
          'Members: Minister of Finance (Chair); Minister of Budget and National Planning; '
          'Chief Economic Adviser to the President; Permanent Secretary, Federal Ministry of '
          'Finance; Deputy Governor (Operations), CBN; Special Adviser to the President on '
          'National Assembly Matters; Senior Special Assistant to the President on Millennium '
          'Development Goals; Accountant-General of the Federation; DG, Budget Office of the '
          'Federation; DG, Bureau of Public Procurement; DG, Debt Management Office; a '
          'representative of the SGF. Meets **at least quarterly** to review performance and '
          'approve Cash Plans, and authorises publication of quarterly Cash Performance '
          'Reports.'},
    {'p': '**Cash Management Technical Committee** — drawn from key MDAs, providing technical '
          'support to the FCMPC, coordinating MDA/stakeholder activities and undertaking '
          'analytical work ahead of ministerial meetings. Membership: Director Fund, OAGF '
          '(Chair); Director, Cash Management Department, FMF; Director Expenditure, BOF; '
          'Director, Portfolio Management, DMO; Director, Banking and Payment System, CBN; '
          'Director, Revenue Accounting, FIRS; Directors of Finance and Accounts of key MDAs '
          '(State House, FMWH, Power, Agriculture, Transport, etc.).'},
    {'p': '**MDA cash management** — each MDA should: have its own cash planning/forecasting '
          'mechanism, with the Accounting Officer overall responsible for cash resources; '
          'consider its Procurement Plan and Annual Cash Plan against budget objectives, needs '
          'and government priority; review actual budget out-turn and address mitigating '
          'factors; and, at a minimum, assign an officer to enter/review departmental needs '
          'into **GIFMIS**, consolidate MDA cash needs for the CMU in the OAGF Funds '
          'Department, confirm cash payment needs are supported by legal/financial commitments '
          'in GIFMIS, and assign a staff counterpart to the CMU.'},
    {'h4': 'Other Ministry of Finance controls'},
    {'ol': [
      'Issuance of financial authorities;',
      'Compilation and tentative approval of the Nation\'s budget;',
      'Issuance of budgetary guidelines;',
      'Issuance of financial regulations;',
      'Issuance of financial circulars.',
    ]},
  ]},

  {'n': '18.6', 't': 'Treasury control — Office of the Accountant-General of the Federation (OAGF)', 'b': [
    {'p': 'Responsibilities of the Accountant-General:'},
    {'ol': [
      'Ensure government funds are used judiciously for the purposes for which they are '
      'earmarked;',
      'Bear overall responsibility for total government expenditure;',
      'Keep the necessary books of account recording all receipts and expenditure of the '
      'various ministries and departments; and',
      'Exercise supervision and checks over the accounting records of **Non-Self-Accounting '
      'Units**, through the Treasury Department.',
    ]},
    {'h4': '(a) Treasury Inspection Questionnaires'},
    {'def': {'t': 'Treasury Inspection Questionnaire', 'd': 'a set of standard questions to be '
                  'answered, and a list of documents to be made available, during a visit to '
                  'an Accounts Department, used by the Accountant-General\'s representatives '
                  'to perform appraisal/control functions.'}},
    {'p': '**Advantages:** they help the inspector complete the assignment without omission; '
          'they clearly state the required standard of performance; they state the '
          'requirements to be met; and they detail the level of assignment required.'},
    {'h4': '(b) Inspectorate department'},
    {'p': 'Inspectorate Officers visit MDAs to evaluate the internal control system, ensuring '
          'the accounting system and books conform to approved regulations. Functions:'},
    {'ol': [
      'Inspection of accounting records, documents and books of Federal MDAs, checking '
      'compliance with rules/regulations and internal controls;',
      'Investigation of fraud and losses of funds/stores in Federal MDAs;',
      'Permanent Board of Survey, and enquiry into cash/stores losses in Federal ministries;',
      'Losses committee, handling cases and write-offs of losses.',
    ]},
    {'h4': '(c) Funds department'},
    {'ol': [
      'Managing the Federation Account, Consolidated Revenue Fund and other public funds;',
      'Cash backing and cash management;',
      'Loans servicing;',
      'Regular reconciliation of government accounts with banks, etc.;',
      'Fiscal accounts; and',
      'Maintenance of the Federal Government\'s expenditure pattern.',
    ]},
    {'h4': '(d) Department of audit monitoring'},
    {'p': 'The OAGF dispatches Internal Auditors to Ministries and Self-Accounting departments '
          'to appraise the effectiveness of existing internal checks. The department carries '
          'out, on the Accountant-General\'s behalf:'},
    {'ol': [
      'Control and supervision of the pool of Internal Auditors in Federal MDAs;',
      'Performing and monitoring all Internal Audit duties in Federal ministries and Federal '
      'Pay Offices; and',
      'Collating and analysing Internal Audit reports from all ministries and agencies.',
    ]},
  ]},

  {'n': '18.7', 't': 'Departmental controls', 'b': [
    {'p': 'Control measures instituted in the spending organisations, to ensure proper, '
          'optimal use of funds — accountability is enhanced by routine compliance with '
          'institutionalized internal controls, and specific controls exist for each type of '
          'financial transaction.'},
    {'h4': 'Revenue controls'},
    {'ol': [
      'All revenue must be timely collected as it falls due;',
      'The actual amount collected must be accounted for and remitted to the Treasury;',
      'All revenues must be paid in gross to the **TSA (Treasury Single Account)**;',
      'Monthly returns of revenue must be rendered to the appropriate institutions.',
    ]},
    {'h4': 'Expenditure control variables'},
    {'p': '**(a)** Heads of departments (Vote Controllers) issue **Activity and Expenditure '
          'Initiation Forms** for expenditure activity, and issue departmental accounting '
          'manuals — codes of instruction regulating financial administration and accounting '
          'practices, containing accounting procedures, chart of accounts, keeping of '
          'accounts, and financial-statement formatting/preparation, approved by the Vote '
          'Controller, Accountant-General and Auditor-General.'},
    {'p': '**(b)** Spending officers/Heads of Departments, as primary controllers of votes, '
          'are obliged (under the Financial Regulations) to keep accounts monitoring and '
          'rendering stewardship for approved/allocated funds, and to state commitments made '
          'against those funds.'},
    {'p': '**(c)** Vote Controllers, for proper and tight expenditure control, must ensure:'},
    {'ol': [
      'Every expenditure is a lawful charge against the public fund;',
      'There are funds to meet the expenditure;',
      'Stores/Services Received Advices (SRAs) are checked;',
      'Payments are in order in all respects, conforming to regulations, with prices/rates '
      'fair and reasonable relative to current local rates;',
      'Payment vouchers are duly signed with relevant supporting documents.',
    ]},
    {'h4': 'Other departmental controls'},
    {'ul': [
      'Relevant authorities must properly authorise all payments — an officer making an '
      'unauthorised payment can be charged for an offence.',
      'All amounts payable must not exceed approved amounts; variations need cogent '
      'explanation and subsequent approval.',
      'Payments go only to the right persons entitled to be paid (suppliers, contractors, '
      'staff), never to officials themselves or other insiders.',
      'Correct classification is applied, showing the head/sub-head to which expenditure '
      'relates.',
      'Payments are made only for the purpose for which funds are meant — no diversion.',
      'All payments must be approved by the designated authority, supported by the '
      'appropriate payment voucher, and pre-audited.',
      'Documents accompanying payment must support the validity and purpose of the claim.',
      'Payments must be supported by: evidence of funds availability (warrants/AIEs); '
      'Certificate of No Objection, as appropriate; evidence of Tender Board approval; and '
      'evidence of Federal Executive Council approval for contracts of N50 million and above.',
      '**Mobilisation** must not exceed **15%** of the contract price.',
      'In National Competitive Bidding (NCB), mobilisation must be supported by an '
      'unconditional bank guarantee or insurance bond acceptable to the MDA.',
      'In International Competitive Bidding, mobilisation must be supported by an '
      'unconditional bank guarantee from a banking institution acceptable to the MDA.',
      'Where a contract requires a mobilisation fee, a performance guarantee is required of '
      'not less than **10%** of the contract value, or an amount equal to the mobilisation '
      'fee, whichever is higher.',
      'For NCB and international bidding, the bank guarantee\'s validity remains until full '
      'recovery of the advance payment.',
      'An interim performance certificate is required, approved by the Honourable Minister, '
      'before further payment beyond the initial mobilization payment.',
    ]},
  ]},

  {'n': '18.8', 't': 'Vote book and expenditure control (DVEA)', 'b': [
    {'def': {'t': 'Departmental Vote Expenditure Allocation (DVEA) book — the Vote Book',
              'd': 'a record kept by officers entrusted with total, express control of a '
                  'Ministry/Department\'s expenditure vote, cross-referenced against the '
                  'provision for expenditure in the approved annual estimate. It records all '
                  'expenditure, including liabilities incurred, against the votes allocated. '
                  'The **Accounting Officer** controls the Vote Book.'}},
    {'h3': '18.8.1 Purposes of keeping a vote book'},
    {'ol': [
      'To have absolute control over expenditure;',
      'To prevent reckless spending or abuse of a vote in a Ministry/Department;',
      'To ensure votes for a particular expenditure are not channelled to expenditures not '
      'provided for in the approved budget;',
      'To reveal balances available;',
      'To show all commitments and outstanding liabilities.',
    ]},
    {'h3': '18.8.2 Maintenance of the vote book'},
    {'p': 'Maintained by an officer with integrity, experience, competence and dedication, '
          'not below the rank of **Senior Finance Assistant**, always supervised by another '
          'senior officer so its objectives are not neglected.'},
    {'h3': '18.8.3 Format of a vote book'},
    {'p': 'A DVEA book has 15 columns: **(1)** Line No.; **(2)** Date; **(3)** Voucher No. '
          '(from the Voucher Register); **(4)** Particulars (payee name); **(5)** Payments '
          '(gross payment on the voucher); **(6)** Cumulative payment (total to date); '
          '**(7)** Balance (authorised amount less column 6); **(8)** Liability reference '
          '(an LPO, job order or agreement entered into but not yet executed/supplied); '
          '**(9)** Liability incurred (the actual amount recognised once supply/execution '
          'occurs); **(10)** Liability cleared (posted once the liability in column 9 is '
          'cleared and entered in column 5); **(11)** Outstanding liabilities (cumulative '
          'liability to date); **(12)** Remarks (indebtedness to the contractor/supplier in '
          'column 9); **(13)** Uncommitted balance (column 7 less all liabilities incurred); '
          '**(14)–(15)** Line No. references (to lines cleared, and repeating column 1).'},
    {'eg': {'tag': 'Study text', 't': 'Vote Book illustration — Ministry of Education, '
      'August 2021 (stationery)', 'open': True, 'q': [
      {'p': 'The Ministry of Education\'s DVEA book shows: authorised appropriation for the '
            'year N1,000,000. 2/8/2021 — paid N45,000 to Odunuga Bookshop, PV 004. 6/8/2021 — '
            'paid N50,000 for stencils to Abiola Bookshop, PV 005. 10/8/2021 — issued LPO '
            '0044 to Lambus Bookshop for photocopying paper, N100,000. 18/8/2021 — settled '
            'Lambus on account, PV 006. 23/8/2021 — paid N20,000 for stapling pins/staplers '
            'to Orita Bookshop, PV 007. 26/8/2021 — PV 0008 raised for N120,000 for typing '
            'sheets, CSS Bookshop. 27/8/2021 — issued LPO 00045 for N300,000 to Olorus Stores '
            'Ltd for duplicating paper. 30/8/2021 — settled N300,000 on PV 009 for carbon '
            'paper, Dossy Bookshop. 31/8/2021 — settled Olorus Stores Ltd on account, PV 010. '
            'Prepare the Vote Book.'}],
      'a': [
      {'table': {'cap': 'Ministry of Education — Vote Book (Stationery), August 2021 '
                       '(N)', 'align': 'lllllllll', 'head': ['Line', 'Date', 'PV No.',
        'Particulars', 'Payment', 'Cumulative payment', 'Balance', 'Liability incurred/'
        'cleared', 'Outstanding liability'], 'rows': [
        ['1', '1/8', '—', 'Auth. Appropriation', '—', '—', '1,000,000', '—', '—'],
        ['2', '2/8', '004', 'Odunuga Bookshop', '45,000', '45,000', '955,000', '—', '—'],
        ['3', '6/8', '005', 'Abiola Bookshop', '50,000', '95,000', '905,000', '—', '—'],
        ['4', '10/8', '—', 'LPO 0044 to Lambus Bookshop', '—', '95,000', '905,000',
         'Incurred: 100,000', '100,000'],
        ['5', '18/8', '006', 'Lambus Bookshop — settlement of LPO', '100,000', '195,000',
         '805,000', 'Cleared (ref. line 4)', '—'],
        ['6', '23/8', '007', 'Orita Bookshop', '20,000', '215,000', '785,000', '—', '—'],
        ['7', '26/8', '008', 'CSS Bookshop', '120,000', '335,000', '665,000', '—', '—'],
        ['8', '27/8', '—', 'LPO 0045 to Olorus Stores Ltd', '—', '335,000', '665,000',
         'Incurred: 300,000', '300,000'],
        ['9', '30/8', '009', 'Dossy Bookshop', '300,000', '635,000', '365,000', '—', '—'],
        ['10', '31/8', '010', 'Olorus Stores Ltd — settlement', '300,000', '935,000',
         '65,000', 'Cleared (ref. line 8)', '—'],
      ]}},
      {'note': 'By the end of the month, cumulative payments of N935,000 leave a balance of '
               'N65,000 available against the N1,000,000 appropriation, with no outstanding '
               'liabilities — both LPOs (lines 4 and 8) were fully settled and cleared '
               '(lines 5 and 10).'}]}},
    {'h3': '18.8.4 Verification of entries in the vote book'},
    {'p': 'Vouchers must be stamped "Entered in the Vote Book" by the officer controlling '
          'expenditure, and initialled. Entries can also be verified by ensuring: **(a)** '
          'totals in columns 6 and 7 agree with the authorised amount; **(b)** totals in '
          'columns 11 and 13 agree with the amount in column 7.'},
    {'h3': '18.8.5 Functions of the officer controlling expenditure'},
    {'ol': [
      'Ensure the Vote Book is properly maintained, entering all payments accurately;',
      'Forward monthly returns to the vote-issuing ministry/department;',
      'Investigate, report and act on any irregularity discovered in a payment voucher;',
      'Ensure all expenditures are justified;',
      'Ensure votes are applied for the purpose for which they are provided;',
      'Ensure votes remain available throughout the fiscal year, by spreading them evenly;',
      'Demand additional vote provision where incurred liabilities are likely to exceed the '
      'vote obtained.',
    ]},
  ]},

  {'n': '18.9', 't': 'Efficiency Unit', 'b': [
    {'h3': 'Necessity of the Efficiency Unit'},
    {'ul': [
      'Nigeria\'s dependence on crude oil for foreign exchange/revenue makes the economy '
      'vulnerable to shocks in international oil markets, as seen in the impact of oil-price '
      'collapses on external reserves, the Naira exchange rate and revenues.',
      'A disproportionate share of recurrent to capital expenditure has constrained '
      'infrastructure development — spending biased against capital projects is inimical to '
      'growth.',
      'Public-sector work and procurement processes/practices inherently promote or support '
      'wastage and inefficiency.',
      'The need to ensure Government resources are used most efficiently, so citizens get '
      'value for money and more funds are available for capital projects, has never been '
      'greater.',
    ]},
    {'h3': 'Mandate of the Efficiency Unit'},
    {'ol': [
      'Reviewing government spending patterns using budget implementation reports and other '
      'sources;',
      'Working closely with MDAs to review work/procurement processes for specific '
      'expenditure lines;',
      'Agreeing changes or process improvements to reduce wastage and make savings;',
      'Continuously publishing achievements (savings) from such changes;',
      'Identifying and migrating best practices in public spending from other countries to '
      'Nigeria;',
      'Promoting a change in the culture of MDA public spending, towards prudence and '
      'savings;',
      'Collaborating with government institutions whose responsibilities bear on the unit\'s;',
      'Identifying and implementing Price Guidelines and Benchmarking of MDAs, offering '
      '"Quick Wins" and large savings;',
      'Ensuring Government revenues are deployed efficiently, for Value for Money and '
      'Savings, complementing efforts to diversify revenue sources.',
    ]},
    {'h3': 'Composition of the Steering Committee'},
    {'ol': [
      'The Honourable Minister of Finance — Chairman;',
      'The Head of Civil Service of the Federation — Member;',
      'The Auditor-General for the Federation — Member;',
      'The Accountant-General of the Federation — Member;',
      'Four members from the private sector;',
      'Head of the Efficiency Unit — Secretary.',
    ]},
    {'h3': 'Benefits of the Efficiency Unit'},
    {'ol': [
      'An internal government tool, saving costs, providing learning opportunities and long-'
      'term benefits;',
      'Participatory (MDAs are involved) rather than top-down, easing acceptance and '
      'institutionalisation of an efficiency culture;',
      'Has the potential to introduce other public-sector reforms for the public good.',
    ]},
  ]},

  {'n': '18.10', 't': 'Finance and General-Purpose Committee (FGPC)', 'b': [
    {'h3': 'Composition'},
    {'ol': [
      'At least three Board members, appointed by the Board on the Chairman\'s '
      'recommendation;',
      'One member also serves as the Committee\'s Chairman;',
      'Members should aim to serve a term of at least three years;',
      'Vacancies are filled by the Board, which may appoint members for a shorter term;',
      'Members serve until their successors are elected, or earlier resignation/removal;',
      'Any member may be removed/replaced, for any reason, by a majority Board vote.',
    ]},
    {'h3': 'Responsibilities'},
    {'p': 'The Committee periodically reviews and reports/recommends to the Board on:'},
    {'ol': [
      'Management of the organisation\'s finances;',
      'Control over the organisation\'s property, revenue and expenditure;',
      'Direction of the deposit and investment of subscriptions, donations and other monetary '
      'income;',
      'Appraisal of the financial implications of proposed activities;',
      'Consideration of annual budgets and accounts;',
      'Regular reports on performance against budget for a financial year;',
      'Assessment of the organisation\'s relationships with other bodies, income/expenditure '
      'policies, and audited financial statements with the management letter;',
      'Any other matters submitted by management, including capital expenditures, '
      'divestments, acquisitions, joint ventures and other capital transactions; leases, '
      'short/long-term borrowings and other financing transactions; interest rate swaps and '
      'similar debt-exposure management arrangements; and registration/issuance of debt or '
      'equity securities;',
      'Performing other activities the Committee deems appropriate or the Board requests; '
      'reviewing and reassessing this Charter\'s adequacy; and conducting an annual '
      'performance evaluation, reporting regularly to the Board.',
    ]},
  ]},

  {'n': '18.11', 't': 'Audit committee', 'b': [
    {'p': 'Audit committees are a common private-sector feature, sometimes established for '
          'public-sector-owned enterprises, but much less a feature of non-market public '
          'sector organisations (ministries, local governments). Where established in the '
          'non-market public sector, "audit committee" describes committees of varying '
          'purpose and reporting line, often limited in scope, and typically lacking the '
          '**independent membership** regarded as crucial to a private-sector audit '
          'committee\'s success.'},
    {'h3': 'Composition'},
    {'p': 'At least **3 members**, all non-executive directors, a majority of whom are '
          'independent. The Chairman is independent and **not** the Chairman of the Board. At '
          'least one member has relevant qualifications.'},
    {'h3': 'Roles'},
    {'p': 'Set out in written terms of reference, including:'},
    {'ol': [
      'Monitoring the integrity of the financial statements and formal announcements on '
      'financial performance, reviewing significant financial reporting judgements;',
      'Reviewing internal financial controls, and (unless addressed by a separate risk '
      'committee or the board itself) reviewing internal control and risk management systems;',
      'Monitoring and reviewing the effectiveness of the internal audit function;',
      'Recommending to the board (for shareholder approval) the appointment, re-appointment '
      'and removal of the external auditor, and approving the auditor\'s remuneration and '
      'terms of engagement;',
      'Reviewing and monitoring the external auditor\'s independence, objectivity and the '
      'effectiveness of the audit process;',
      'Developing and implementing policy on engaging the external auditor for non-audit '
      'services, and reporting to the board on matters needing action or improvement.',
    ]},
  ]},

  {'n': '18.12', 't': 'Chapter review', 'b': [
    {'p': 'Financial control in the public sector involves control of public revenue and '
          'expenditure, deciding on government objectives and priorities, and devising proper '
          'systems for information flow and control — as well as monitoring the outcome of '
          'finance usage. The chapter covered revenue and expenditure control techniques, with '
          'emphasis on the Executive, Legislative, Ministry of Finance, Treasury and '
          'Departmental controls, plus financial authorisation measures — expenditure '
          'authorisation procedures, warrants, financial encumbrance and drawing limits.'},
  ]},

  {'n': '18.13', 't': 'End of chapter review questions', 'b': [
    {'h3': 'Section A'},
    {'eg': {'tag': 'Study text', 't': 'Questions 1–10 with answers', 'open': True, 'q': [
      {'ol': [
        'Issuance of financial authorities is one of the control measures adopted by: '
        '(i) The Treasury  (ii) The Ministry of Finance  (iii) The Extra-Ministerial '
        'Departments. (A) (i) only  (B) (ii) and (iii)  (C) (iii) only  (D) (i) and (ii)  '
        '(E) (ii) only',
        'Which of the following organs approve the Nation\'s Budget? (A) The National '
        'Assembly  (B) The Executive  (C) The Minister of Finance  (D) The Accountant-'
        'General of the Federation  (E) The Auditor-General for the Federation',
        'The Legislative body that performs a post-mortem function on financial matters is '
        'the (A) Audit Alarm Committee  (B) Treasury Board  (C) Public Accounts Committee  '
        '(D) The Joint Committee of the Senate and House of Representatives  (E) The Board '
        'of Survey',
        'Which ONE of the following arms of government carries out monetary and fiscal '
        'policies as a means of control over government expenditure? (A) The Industries and '
        'Extra-Ministerial Departments  (B) The Ministry of Finance  (C) The Legislature  '
        '(D) The Executive  (E) The Judiciary',
        'The independent organ of government that reviews all contracts awarded which are of '
        'significant value is (A) The procurement body  (B) The Board of enquiry  (C) The '
        'Board of Survey  (D) The Budget Monitoring and Price Intelligence Unit  (E) The '
        'Federal Executive Council',
        'Issuance of budgetary guidelines is one of the ways by which the … arm of government '
        'controls expenditure.',
        'What is the mechanism of government for ensuring strict compliance with the '
        'openness, competition and cost-accuracy rules and procedures in contract awards?',
        'The officer saddled with the responsibility of performing purely regularity and '
        'compliance audit on government accounts and reporting to the National Assembly is '
        '…',
        'The authority that confers on government officers controlling expenditure the power '
        'to incur expenditure votes is called …',
        'The organ of government that issues guidelines on the preparation of budgets is the '
        '…',
      ]}],
      'a': [
      {'p': '**1.** E  **2.** A  **3.** C  **4.** B  **5.** D  **6.** Executive  '
            '**7.** Due process  **8.** Auditor-General for the Federation  **9.** Warrant  '
            '**10.** Ministry of Finance'}]}},
    {'h3': 'Section B'},
    {'eg': {'tag': 'Study text', 't': 'Questions 1–4 with answers', 'open': True, 'q': [
      {'ol': [
        'What are the main roles of the National Assembly in planning and monitoring public '
        'expenditure?',
        'List the basic controls exercised over government expenditure to prevent '
        'indiscriminate spending of funds.',
        'The Legislative Control deals with various measures Parliament employs to safeguard '
        'public funds. Discuss five ways by which Parliament exercises such financial '
        'controls.',
        '(a) Explain the purpose of the Efficiency Unit. (b) State the benefits of the '
        'Efficiency Unit for Nigeria.',
      ]}],
      'a': [
      {'h4': '1. Main roles of the National Assembly'},
      {'ol': [
        'Ratification of the monetary and fiscal policies adopted by the Executive.',
        'Compilation and ultimate approval of the Nation\'s budget.',
        'Ratification of the appointment of the Auditor-General.',
        'Appointment of the Public Accounts Committee.',
        'Monitoring of the implementation of the Budget.',
        'Guarding against extra-budgetary spending, and ensuring money is spent for which it '
        'is meant.']},
      {'h4': '2. Basic controls exercised over government expenditure'},
      {'ol': [
        'Financial control (overall).',
        'Legislative control.',
        'Executive control.',
        'Ministry of Finance control.',
        'The Treasury control.',
        'Departmental control.']},
      {'h4': '3. Five ways Parliament exercises legislative control'},
      {'ul': [
        '**Public Finance Committee** — a sub-committee of Parliament, receiving the '
        'Appropriation Bill for the National Assembly\'s consideration.',
        '**Appropriation Committee** — passes the Appropriation Bill into the Appropriation '
        'Act, in effect the whole House of Parliament sitting to authorise the estimates.',
        '**Examination Sub-Committees** — examine individual organisations\' estimates and '
        'monitor their expenditure (oversight functions).',
        '**Public Accounts Committee** — receives audited public accounts and special audit '
        'reports, examines and debates them, and reports findings/recommendations to the '
        'whole house, which acts on that basis.',
        '**The concept of Appropriation** — the procedure making national revenue available '
        'annually to the Executive to finance its programmes, including **Appropriations-in-'
        'Aid** (income departments receive apart from Consolidated Fund releases, which '
        'reduces the amount they need from that Fund).']},
      {'h4': '4(a). Purpose of the Efficiency Unit'},
      {'p': 'In broad terms, its mandate is to review the Federal Government\'s expenditure '
            'profile/pattern and work with MDAs to introduce more efficient processes and '
            'procedures, ensuring Government revenues are deployed efficiently for Value for '
            'Money and Savings — complementing efforts to diversify revenue sources.'},
      {'h4': '4(b). Benefits of the Efficiency Unit for Nigeria'},
      {'ol': [
        'An internal government tool, saving costs and providing learning opportunities and '
        'long-term benefits.',
        'Participatory (MDAs involved) rather than top-down, easing acceptance and '
        'institutionalisation of an efficiency culture.',
        'Potential to introduce other public-sector reforms for the public good.']}]}},
  ]},
 ],
 'formulas': [],
 'focus':
   'The examiner loves matching a control measure to the exact arm that exercises it — '
   'issuance of financial authorities and budgetary guidelines (Ministry of Finance), '
   'monetary/fiscal policy (Executive), post-mortem/PAC review (Legislature), inspection and '
   'audit monitoring (Treasury/OAGF). Memorise virement\'s 10% overhead-cost limit and its '
   'restriction to sub-heads within the same head, and the Vote Book\'s purpose (absolute '
   'expenditure control, revealing balances and outstanding liabilities) rather than its full '
   '15-column layout.',
 'errors': [
   'Confusing virement (sub-head to sub-head, same head, max 10% of overhead-cost estimate) '
   'with a fresh budgetary allocation — virement can never create a new sub-head or '
   'reintroduce a disallowed item.',
   'Treating the Public Accounts Committee as an executive body — it is a Legislative organ '
   'performing post-natal (after-the-fact) review of accounts already audited.',
   'Mixing up the Efficiency Unit (reviews MDA spending patterns for savings) with the Audit '
   'Committee (monitors financial statement integrity and the external/internal audit '
   'process) — both are oversight bodies but with different mandates.',
   'Forgetting that ante-natal control (approving estimates before spending) and post-natal '
   'control (reviewing transactions after payment) are both exercised by the Legislature, not '
   'split between Legislature and Executive.',
 ],
 'quiz': {
  'mcq': [
   {'q': 'An authorised transfer of funds from one sub-head to another sub-head, but within '
         'the same head, is called',
    'o': ['A supplementary appropriation', 'Virement', 'A warrant', 'Appropriation-in-Aid',
          'A vote on account'],
    'a': 1,
    'w': 'Virement moves money between sub-heads of the same head, subject to a 10% cap on '
         'overhead-cost sub-heads, and cannot create a new sub-head.',
    'src': 'Chapter 18.5(b)'},
   {'q': 'Which committee is empowered to examine the Auditor-General\'s reports on fraud or '
         'embezzlement of public funds and report to the National/State Assembly?',
    'o': ['The Finance and General-Purpose Committee', 'The Audit Committee',
          'The Public Accounts Committee (PAC)', 'The Efficiency Unit',
          'The Cash Management Technical Committee'],
    'a': 2,
    'w': 'The PAC specifically examines audited accounts and the Auditor-General\'s report, '
         'exposing waste, corruption or inefficiency and recommending action to the '
         'Assembly.',
    'src': 'Chapter 18.3(d)'},
   {'q': 'The officer below whose rank the Vote Book may not be maintained is a',
    'o': ['Senior Finance Assistant', 'Director of Finance and Accounts', 'Permanent '
          'Secretary', 'Accountant-General', 'Chief Treasury Officer'],
    'a': 0,
    'w': 'The Vote Book must be maintained by an officer of integrity and experience not '
         'below the rank of Senior Finance Assistant, always under a senior officer\'s '
         'supervision.',
    'src': 'Chapter 18.8.2'},
  ],
  'theory': [
   {'q': 'Distinguish "ante-natal" from "post-natal" legislative control, and state the '
         'constitutional limit on the President\'s power to spend without an Appropriation '
         'Act.',
    'marks': 6,
    'a': [
      {'p': '**Ante-natal control** occurs when the legislature considers and approves the '
            'estimates the President submits, before any spending. **Post-natal control** is '
            'the legislature\'s review of transactions after payment has been made. Under '
            'Section 82 of the 1999 Constitution, the President may spend from the '
            'Consolidated Revenue Fund to run the Federation\'s administration for not more '
            'than **six months**, or until the Appropriation Act comes into operation, '
            'whichever is earlier.'}],
    'src': 'Chapter 18.3'},
   {'q': 'State the conditions under which an Accounting Officer may apply for virement.',
    'marks': 8,
    'a': [
      {'ol': [
        'The amount vired from any sub-head, within a financial year, under overhead costs '
        'must not exceed 10% of the approved estimate for each such sub-head.',
        'Virement must not create a new sub-head, or re-introduce items disallowed during the '
        'budget process by the National Assembly.',
        'Virement does not apply to Auditor-General queries on improper expenditure already '
        'incurred.',
        'Approval is by the National Assembly, conveyed by the Minister of Finance to the '
        'MDA.',
        'A register must be kept of all virements made.',
        'Details of authorised virements must be forwarded within one month of approval to '
        'the ministry concerned, and to the Accountant-General and Auditor-General for the '
        'Federation.']}],
    'src': 'Chapter 18.5(b)'},
   {'q': 'List any five purposes served by keeping a Departmental Vote Expenditure Allocation '
         '(Vote) Book.',
    'marks': 5,
    'a': [
      {'ol': [
        'To have absolute control over expenditure.',
        'To prevent reckless spending or abuse of a vote in a Ministry/Department.',
        'To ensure votes for a particular expenditure are not channelled to items not '
        'provided for in the approved budget.',
        'To reveal balances available.',
        'To show all commitments and outstanding liabilities.']}],
    'src': 'Chapter 18.8.1'},
  ]},
}
